### ISSUE TITLE
Does not compile with "CoffeeScript version 1.10.0"

### ISSUE THREAD

**Issue by sprig** [andrusha/mathml-chrome#4]
Hi,

after cloning the repo, I get the following:

``` sh
% make         
echo "Compiling coffee script"
Compiling coffee script
coffee --compile --lint --join ./release/mathml-chrome.js lib.coffee cached_storage.coffee mathml-chrome.coffee
/usr/lib/node_modules/coffee-script/lib/coffee-script/optparse.js:51
            throw new Error("unrecognized option: " + arg);
            ^

Error: unrecognized option: --lint
  at OptionParser.exports.OptionParser.OptionParser.parse (/usr/lib/node_modules/coffee-script/lib/coffee-script/optparse.js:51:19)
  at parseOptions (/usr/lib/node_modules/coffee-script/lib/coffee-script/command.js:550:29)
  at Object.exports.run (/usr/lib/node_modules/coffee-script/lib/coffee-script/command.js:54:5)
  at Object.<anonymous> (/usr/lib/node_modules/coffee-script/bin/coffee:7:41)
  at Module._compile (module.js:398:26)
  at Object.Module._extensions..js (module.js:405:10)
  at Module.load (module.js:344:32)
  at Function.Module._load (module.js:301:12)
  at Function.Module.runMain (module.js:430:10)
  at startup (node.js:141:18)
  at node.js:980:3

Makefile:24: recipe for target 'dev' failed
make: *** [dev] Error 1

% coffee -v
CoffeeScript version 1.10.0

% coffee --help

Usage: coffee [options] path/to/script.coffee -- [args]

If called without options, `coffee` will run your script.

  -b, --bare         compile without a top-level function wrapper
  -c, --compile      compile to JavaScript and save as .js files
  -e, --eval         pass a string from the command line as input
  -h, --help         display this help message
  -i, --interactive  run an interactive CoffeeScript REPL
  -j, --join         concatenate the source CoffeeScript before compiling
  -m, --map          generate source map and save as .js.map files
  -n, --nodes        print out the parse tree that the parser produces
      --nodejs       pass options directly to the "node" binary
      --no-header    suppress the "Generated by" header
  -o, --output       set the output directory for compiled JavaScript
  -p, --print        print out the compiled JavaScript
  -r, --require      require the given module before eval or REPL
  -s, --stdio        listen for and compile scripts over stdio
  -l, --literate     treat stdio as literate style coffee-script
  -t, --tokens       print out the tokens that the lexer/rewriter produce
  -v, --version      display the version number
  -w, --watch        watch scripts for changes and rerun commands

```

This is for archlinux with coffee-script 1.10.0-3

**Comment by sprig** [comment]
after removing the --lint option from the dev target everything compiles without a hitch.

**Comment by andrusha** [comment]
Thanks for the report! Could you make an PR for it? This piece hadn't been maintained in awhile, not sure if manifest is still up to date with the recent Chrome.

**Comment by sprig** [comment]
Sure. I also needed to change "closure-compiler" to 
"closure" - I'm not sure whether it is just my distro deciding to name the executable differently than yours, or the upstream changing their naming. Any idea? I haven't touched the manifest and it appears to work fine, except for the fact that the options page always shows an empty list of "enabled sites".

**Comment by andrusha** [comment]
@sprig could be your distro, I recall writing this extension real while ago, so things could've changed. The `closure-compiler` should refer to this https://developers.google.com/closure/compiler/?hl=en

**Comment by sprig** [comment]
I just looked. It appears that the naming is somewhat arbitrary since the executable is a shell script created ad-hoc. Regardless, I'll make a PR that addresses this as well.

**Comment by andrusha** [comment]
Thanks, much appreciated!

**Comment by andrusha** [comment]
I guess since #5 was merged, this can be closed.
